---
  - name: Application Dependencies Setup
    hosts: "{{ specific_host }}"
    gather_facts: no
    become: yes

    tasks:

      ###################################################################################################################

      - name: Extract java package
        command: "sudo tar -zxvf /opt/jdk-8u202-linux-x64.tar.gz -C /usr/java/"
        become: yes
        become_user: root
        register: java_extracted

      - name: Backup existing /etc/profile file
        copy: 
          src: /etc/profile
          dest: /etc/profile.BAK
          remote_src: yes
        become: yes
        become_user: root

      - name: Add JAVA HOME path to /etc/profile
        lineinfile:
          path: /etc/profile
          line: "{{ item }}"
          insertafter: '^# will prevent the need for merging in future updates.'
        become: yes
        become_user: root
        with_items:
          - export JAVA_HOME=/usr/java/{{java_extracted.stdout_lines[0]}}
          - export PATH=$JAVA_HOME/bin:$PATH

      ###################################################################################################################
      
      - name: Extract tomcat
        unarchive:
          src: "/opt/source/apache-tomcat-{{tomcat_version}}.tar.gz"
          dest: /opt/source/
          remote_src: yes
        register: tomcat_extracted

      - name: Formating tomcat tomcat name
        set_fact:
          tomcat_directory_name: "{{ tomcat_extracted.src | basename | regex_replace('\\.tar\\.gz$', '') }}"

      - name: Move extracted tomcat directory to /opt directory
        move: 
          src: "/opt/source/{{tomcat_directory_name}}"
          dest: "/opt/{{update_tomcat_directory}}"

      - name: Create tomcat user
        command: "useradd -d /opt/tomcat -s /bin/nologin tomcat"
        become: yes
        become_user: root
        register: create_tomcat_user

      - name: Change new tomcat directory ownership 
        file:
          path: "/opt/{{update_tomcat_directory}}"
          owner: tomcat
          group: tomcat
          mode: "0775"
          recurse: yes
          # remote_src: yes
        register: change_ownership

      - name: Create updated tomcat.service file with content
        copy:
          content: |
            [Unit]
            Description=Apache Tomcat Application Container
            Wants=network.target
            After=network.target

            [Service]
            Type=forking

            Environment=JAVA_HOME=/opt/openjdk11.0.11.9

            Environment=CATALINA_PID=/opt/{{update_tomcat_directory}}/temp/tomcat.pid
            Environment=CATALINA_HOME=/opt/{{update_tomcat_directory}}
            Environment='CATALINA_OPTS=-Xms128M -Xmx256M -Djava.net.preferIPv4Stack=true -Dapplication.module=job -Dapplication.environment.properties=/opt/config/PNDS/TSconf'
            Environment='JAVA_OPTS=-Djava.awt.headless=true'
            Environment='JAVA_OPTS=-Djava.library.path=/opt/cloudhsm/lib'
            Environment=SPRING_APPLICATION_JSON='{"TOKENGATEWAY": {"COREPATH": "file:/opt/config/","LOG4JAPI": "file:/opt/config/log4j2-api.xml"}}'

            ExecStart=/bin/bash /opt/{{update_tomcat_directory}}/bin/startup.sh
            ExecStop=/bin/bash /opt/{{update_tomcat_directory}}/bin/shutdown.sh
            SuccessExitStatus=143

            User=tomcat
            Group=tomcat
            UMask=0007
            Environment='UMASK=002'
            RestartSec=10
            Restart=always

            [Install]
            WantedBy=multi-user.target
          dest: /etc/systemd/system/{{ update_tomcat_service }}.service
        register: tomcat_service

      - name: Enable updated httpd service
        command: "systemctl enable {{ update_tomcat_service }}.service"
        become: yes

      - name: Start updated tomcat service
        command: "systemctl start {{ update_tomcat_service }}.service"
        become: yes
        async: 100
        poll: 5
        register: start_tomcat

      - name: Status check on the updated tomcat service
        command: "systemctl status {{ update_tomcat_service }}.service"
        become: yes
        register: upgraded_tomcat_status_check
        
      - name: Display status check on the updated tomcat service
        debug:
          var: upgraded_tomcat_status_check

      - name: Delete downloaded httpd installer
        file: 
          path: "/opt/source/{{ tomcat_version }}.tar.gz"
          state: absent

      ###################################################################################################################

      