---
  - name: test service facts
    hosts: httpd_servers
    gather_facts: no
    become: yes
    tasks:
      - name: Gather facts about services
        service_facts:

      - name: Display services
        ansible.builtin.debug:
          var: ansible_facts.services