---
  - name: Httpd upgrade task
    hosts: httpd_servers
    gather_facts: no
    become: yes

    tasks:
      - name: Stop existing tomcat service
        command: "systemctl stop tomcat"
        become: yes
        async: 100
        poll: 5

      - name: Disable existing tomcat service
        command: "systemctl disable tomcat"

      - name: Existing tomcat status check
        command: "systemctl status tomcat"
        register: existing_tomcat_status
        ignore_errors: yes

      - name: Display existing tomcat status check
        debug:
          var: existing_tomcat_status

      - name: Download new apache tomcat version
        get_url: 
          url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.22/bin/apache-tomcat-9.0.22.tar.gz
          dest: /opt/source/
          validate_certs: no
        register: tomcat_download

      - name: Extract tomcat
        unarchive:
          src: /opt/source/tomcat.tar.gz
          dest: /opt/source/
          remote_src: yes
        register: tomcat_extracted

      - name: 