---
  - name: Tomcat upgrade task
    hosts: "{{ specific_host }}"
    gather_facts: no
    become: yes

    ## tomcat_installer
    ## existing_tomcat_service
    ## existing_tomcat_directory
    ## update_tomcat_service
    ## update_tomcat_directory

    tasks:
      - name: Stop existing tomcat service
        command: "systemctl stop {{ existing_tomcat_service }}.service"
        become: yes
        async: 100
        poll: 5

      - name: Disable existing tomcat service
        command: "systemctl disable {{ existing_tomcat_service }}.service"

      - name: Existing tomcat status check
        command: "systemctl status {{ existing_tomcat_service }}.service"
        register: existing_tomcat_status
        ignore_errors: yes

      - name: Display existing tomcat status check
        debug:
          var: existing_tomcat_status

      - name: Download new apache tomcat version
        get_url: 
          url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.22/bin/{{ tomcat_installer }}.tar.gz
          dest: /opt/source/
          validate_certs: no
        register: tomcat_download

      - name: Display tomcat_download
        debug:
          var: tomcat_download

      - name: Extract tomcat
        unarchive:
          src: "{{ tomcat_download.dest }}"
          dest: /opt/source/
          remote_src: yes
        register: tomcat_extracted

      - name: Display tomcat_extracted
        debug:
          var: tomcat_extracted

      - name: Formating tomcat tomcat name
        set_fact:
          httpd_directory_name: "{{ tomcat_extracted.src | basename | regex_replace('\\.tar\\.gz$', '') }}"

      # - name: Move extracted tomcat directory to /opt directory
      #   move: 
      #     src: 
      #     dest: 