---
  - name: Multi Variable Test
    hosts: "{{ specific_host }}"
    gather_facts: no
    become: yes

    tasks:
      - name: Include variable file
        include_vars:
            file: tomcat_variables.yml

      - name: Status check on the updated tomcat service
        command: "systemctl status {{ item.service }}.service"
        become: yes
        with_items: "{{ server }}"
        delegate_to: "{{ item.hostname }}"
        register: upgraded_tomcat_status_check
        
      - name: Display status check on the updated tomcat service
        debug:
          var: upgraded_tomcat_status_check
