---
  - name: Multi Variable Test
    hosts: "{{ server }}"
    gather_facts: no
    become: yes
      vars:
        server_name: "{{server}}"
        instance_name: "{{instance}}"

    tasks:
      - name: Include vars json
        include_vars:
            file: tomcat_variables.yml
      
      - set_fact:
          target_server: "{{lookup('vars',server)}}"
          target_system: "{{lookup('vars',server)[instance]}}" 
          target_instance: "{{lookup('vars',server)[instance]}}"

      - name: Status check on the updated tomcat service
        command: "systemctl status {{ existing_tomcat_service }}.service"
        become: yes
        register: upgraded_tomcat_status_check
        
      - name: Display status check on the updated tomcat service
        debug:
          var: upgraded_tomcat_status_check
