---
  - name: Java update task
    hosts: "{{ specific_host }}"
    gather_facts: no
    become: yes

    tasks:
      - name: Download new apache tomcat version
        get_url: 
          url: "{{ java_package_url }}"
          dest: /opt/source/
          validate_certs: no
        register: java_download

      - name: Extract java package
        command: "tar -zxvf {{ java_download.dest }} -C /opt/source/"
        become: yes
        register: java_extracted

      - name: Move extracted java directory to /usr/java directory
        move: 
          src: "/opt/source/{{java_extracted.stdout_lines[0]}}"
          dest: "/usr/java/{{java_extracted.stdout_lines[0]}}"