---
  - name: Change Password Windows
    hosts: "{{ hostname }}"
    gather_facts: no

    tasks:
      - name: Change Administrator Password
        win_user:
          name: Administrator
          password: "{{ newpassword }}"
          state: present