---
  - name: test user input
    hosts: httpd_servers
    gather_facts: no
    become: yes

    vars_prompt:
      - name: existing_httpd_service_name
        prompt: "Please input existing httpd service name"
        private: no

      - name: upgrade_httpd_version
        prompt: "Please input the new httpd version to be downloaded"
        private: no

      - name: apache_name
        prompt: "Please input desired new apache folder name"
        private: no

    tasks:
      - name: display httpd service name
        debug:
          var: existing_httpd_service_name

      - name: display httpd service name
        debug:
          var: upgrade_httpd_version

      - name: display apache name
        debug:
          var: apache_name